# Package overview
# Uncomment the alias as per the requirement.

# alias(
#     name = "Main_application",
#     actual = "//platforms:stm32f407vg_gcc",
#     visibility = ["//visibility:public"]
# )

# Alias for Main application with GCC Compiler.
alias(
    name = "Main_application",
    actual = "//platforms:stm32l041e6_gcc",
    visibility = ["//visibility:public"]
)


# Alias for PDS application with GCC Compiler.
# alias(
#     name = "Main_application",
#     actual = "//platforms:stm32l041e6_gcc",
#     visibility = ["//visibility:public"]
# )


# Alias for nRF application with GCC Compiler.
# alias(
#     name = "nRF_application",
#     actual = "//platforms:nRF52840_xxAA_gcc",
#     visibility = ["//visibility:public"]
# )

