# Package overview
# Uncomment the alias as per the requirement.

alias(
    name = "stm32f4_iar",
    actual = "//platforms:stm32f407VG_iar",
    visibility = ["//visibility:public"]
)

alias(
    name = "stm32f4_gcc",
    actual = "//platforms:stm32f407VG_gcc",
    visibility = ["//visibility:public"]
)
# Alias for Main application with IAR Compiler.
alias(
    name = "Main_application_iar",
    actual = "//platforms:stm32u585oi_iar",
    visibility = ["//visibility:public"]
)

# Alias for Main application with GCC Compiler.
alias(
    name = "Main_application_gcc",
    actual = "//platforms:stm32u585oi_gcc",
    visibility = ["//visibility:public"]
)

# Alias for PDS application with GCC Compiler.
alias(
    name = "PDS_application",
    actual = "//platforms:stm32l041e6_iar",
    visibility = ["//visibility:public"],
)
