alias(
    name = "stm32f4_iar",
    actual = "//platforms:stm32f407VG_iar",
    visibility = ["//visibility:public"]
)

alias(
    name = "stm32f4_gcc",
    actual = "//platforms:stm32f407VG_gcc",
    visibility = ["//visibility:public"]
)
