# Package description.

# Target description.
#cc_test(
#  name = "test",
#  srcs = glob(["**/*.cpp"]),
#  deps = [
#    "//examples/algorithm",
#  ],
#  size = "small",
#)

cc_binary(
  name = "runner",
  srcs = glob(["runner.c"]),
)

